### ISSUE TITLE
Можно ли увидить вашу магстерскую диссертацию?

### ISSUE THREAD

**Issue by Filipp-Druan** [Armaxis/jmg#16]
Здравствуйте!
Вы на хабре выкладывали ссылку на вашу магстерскую диссертацию. Ныне она не доступна. Не могли бы вы дать на неё ссылку? Очень хочется почитать. Кстати, скажите пожалуйста, насколько трудно повторить вашу программу, если в музыке я дуб дубом? Можно ли сделать это только по вашей диссертации?
Заранее спасибо!

**Comment by Armaxis** [comment]
Спасибо за интерес к моему проекту! Сейчас проще нейросеть научить писать музыку, чем использовать алгоритмический подход, что я делал. Поэтому я бы рекомендовал использовать мой проект как отправную точку, но дальше почитать про современные подходы к генерации музыки.

Презентация и сама магистерская лежат в корне репозитория, вот ссылки. Дайте знать если они не открываются!

https://github.com/Armaxis/jmg/blob/master/paper.docx
https://github.com/Armaxis/jmg/blob/master/presentation.pdf

**Comment by Filipp-Druan** [comment]
Я не нащёл ещё ни одной сети, которая бы генерировала последовательность нот. Все дают сразу аудиодорожку. Да и результат мне не очень нравится. Просто у меня есть видео на ютубе и я хочу сгенерировать музыку для него на фон. А идёт видео минут двадцать.
Файлы открылись, спасибо!

**Comment by Armaxis** [comment]
Если вам нужно просто сгенерировать музыку, то можно попробовать запустить уже скомпилированное приложение:
http://disk.yandex.com/d/t6Sey2ZNFbdN5

https://ru.wikihow.com/%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D1%82%D0%B8%D1%82%D1%8C-.JAR-%D1%84%D0%B0%D0%B9%D0%BB

**Comment by Filipp-Druan** [comment]
Пытаюсь запустить джар файл из архива
java -jar "Music Generator.jar" 
А он:
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.IllegalAccessError: class player.RealtimePlayer (in unnamed module @0x6e75aa0d) cannot access class com.sun.media.sound.SF2Soundbank (in module java.desktop) because module java.desktop does not export com.sun.media.sound to unnamed module @0x6e75aa0d
	at player.RealtimePlayer.init(RealtimePlayer.java:70)
	at main.Main.launchGenerator(Main.java:37)
	at main.Main.main(Main.java:21)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 2 more

Что мне делать? Как это исправить? Я на Linux.

**Comment by Armaxis** [comment]
Не знаю, это ковыряться, разбираться надо. 



Sent from Mail.ru app for iOS


Thursday, August 10, 2023 at 07:20 -05:00 from ***@***.***  ***@***.***>:
